// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetOdata.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Barcode { get; set; }

    public string ImageDataUrl { get; set; }

    public string Description { get; set; }

    public decimal Rate { get; set; }

    public int BrandId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModifiedOn { get; set; }

    public virtual Brand Brand { get; set; }
}